"use client";
import {useState,useEffect,useRef} from 'react';
import {useSearchParams} from 'next/navigation';
import {Search,X,SlidersHorizontal} from 'lucide-react';
import {catalog,featured,matchesQuery,type Product} from '@/lib/catalog';
import {ProductCard} from './product-card';
import {Dialog} from './dialog';
import {refreshProducts} from '@/motion/photographic';
const priceCeiling=Math.ceil(Math.max(...catalog.map(p=>p.price)));
const tabs=['Alle','Filme','Kameras','Labor','Sofortbild','Bücher','Gutscheine'];
function group(p:Product){if(p.category==='FILME')return 'Filme';if(p.category==='CAMERAS')return 'Kameras';if(p.category.includes('INSTAX')||p.category.includes('POLAROID'))return 'Sofortbild';if(p.category.includes('ZINES')||p.category.includes('BÜCHER'))return 'Bücher';if(/gutschein/i.test(p.name))return 'Gutscheine';return 'Labor'}
export function CatalogShop({initialCategory='Alle'}:{initialCategory?:string}){
 const params=useSearchParams();const [category,setCategory]=useState(params.get('category')||initialCategory);const [query,setQuery]=useState(params.get('q')||'');const [format,setFormat]=useState('Alle');const [brand,setBrand]=useState('Alle');const [process,setProcess]=useState('Alle');const [iso,setIso]=useState('Alle');const [stock,setStock]=useState(false);const [sort,setSort]=useState('selected');const [filters,setFilters]=useState(false);const [maxPrice,setMaxPrice]=useState(priceCeiling);const [mobile,setMobile]=useState(false);const grid=useRef<HTMLDivElement>(null);
 useEffect(()=>{setCategory(params.get('category')||initialCategory);setQuery(params.get('q')||'')},[params,initialCategory]);
 useEffect(()=>{const media=window.matchMedia('(max-width: 700px)');const update=()=>{setMobile(media.matches);if(!media.matches)setFilters(false)};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!grid.current)return;const a=refreshProducts(grid.current);return()=>{a?.revert()}},[category,query,format,brand,process,iso,stock,maxPrice,sort]);
 const brands=Array.from(new Set(catalog.map(p=>p.brand).filter(Boolean))).sort();
 const result=catalog.filter(p=>(category==='Alle'||group(p)===category)&&matchesQuery(p,query)&&(format==='Alle'||p.format===format)&&(brand==='Alle'||p.brand===brand)&&(process==='Alle'||p.process===process)&&(iso==='Alle'||p.iso===iso)&&p.price<=maxPrice&&(!stock||p.inStock)).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='name'?a.name.localeCompare(b.name,'de'):Number(b.inStock)-Number(a.inStock)||(featured.findIndex(p=>p.slug===a.slug)<0?999:featured.findIndex(p=>p.slug===a.slug))-(featured.findIndex(p=>p.slug===b.slug)<0?999:featured.findIndex(p=>p.slug===b.slug)));
 const reset=()=>{setCategory('Alle');setQuery('');setFormat('Alle');setBrand('Alle');setProcess('Alle');setIso('Alle');setStock(false);setMaxPrice(priceCeiling)};
 const chips=[...(category!=='Alle'?[{label:category,remove:()=>setCategory('Alle')}]:[]),...(query?[{label:`Suche: ${query}`,remove:()=>setQuery('')}]:[]),...[{label:format,remove:()=>setFormat('Alle')},{label:brand,remove:()=>setBrand('Alle')},{label:process,remove:()=>setProcess('Alle')},{label:iso==='Alle'?'Alle':`ISO ${iso}`,remove:()=>setIso('Alle')}].filter(c=>c.label!=='Alle'),...(stock?[{label:'Auf Lager',remove:()=>setStock(false)}]:[]),...(maxPrice<priceCeiling?[{label:`bis ${maxPrice} €`,remove:()=>setMaxPrice(priceCeiling)}]:[])];
 const filterContent=<><div className="filter-heading"><span className="eyebrow">LAB / SPEZIFIKATION</span><button onClick={reset}>Zurücksetzen</button></div>{[['Format',format,setFormat,['Alle','35mm','120','110']],['Marke',brand,setBrand,['Alle',...brands]],['Prozess',process,setProcess,['Alle','C-41','Schwarzweiß','E-6']],['ISO',iso,setIso,['Alle',...Array.from(new Set(catalog.filter(p=>p.category==='FILME').map(p=>p.iso).filter(Boolean))).sort((a,b)=>Number(a)-Number(b))]]].map(([label,value,setter,choices])=><label className="filter-select" key={label as string}>{label as string}<select value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{(choices as string[]).map(c=><option key={c}>{c}</option>)}</select></label>)}<label className="price-filter">Maximaler Preis<input aria-label="Maximaler Preis" type="range" min="0" max={priceCeiling} step="1" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/><span>bis {maxPrice.toLocaleString('de-DE')} €</span></label><label className="stock-checkbox"><input type="checkbox" checked={stock} onChange={e=>setStock(e.target.checked)}/> Nur auf Lager (Quellstand)</label><p className="filter-note">Katalogstand: 04.10.2026.<br/>Aktuelle Preise & Verfügbarkeit bestätigt der bestehende Shop.</p></>;
 return <div className="section-wrap shop-page"><div className="page-intro"><span className="eyebrow">DER BILDERFÜRST / ANALOG STORE</span><h1>Dein nächstes Bild<br/><em>beginnt hier.</em></h1><p>Filme, Kameras und gutes Werkzeug. Aus unserem echten Analog Store in Fürth.</p></div><div className="shop-tabs" aria-label="Produktkategorien">{tabs.map(t=><button key={t} aria-pressed={category===t} className={category===t?'selected':''} onClick={()=>setCategory(t)}>{t}</button>)}</div><div className="shop-toolbar"><div className="catalog-search"><Search size={18}/><input aria-label="Im Katalog suchen" placeholder="Film, Marke, ISO oder Format suchen …" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Suchbegriff löschen" onClick={()=>setQuery('')}><X size={17}/></button>}</div><span className="results-count" aria-live="polite">{result.length} Produkte</span><label className="sort-control">Sortieren<select value={sort} onChange={e=>setSort(e.target.value)}><option value="selected">Unsere Auswahl</option><option value="low">Preis aufsteigend</option><option value="high">Preis absteigend</option><option value="name">Name A–Z</option></select></label><button className="filter-mobile" aria-expanded={filters} onClick={()=>setFilters(true)}><SlidersHorizontal size={17}/> Filter</button></div>{chips.length>0&&<div className="active-filters" aria-label="Aktive Filter">{chips.map(c=><button key={c.label} onClick={c.remove} aria-label={`${c.label} entfernen`}>{c.label}<X size={11}/></button>)}</div>}<div className="shop-layout">{!mobile&&<aside className="catalog-filters" aria-label="Produktfilter">{filterContent}</aside>}<div className="catalog-grid" ref={grid}>{result.length?result.map((p,i)=><ProductCard product={p} index={i} key={p.slug}/>):<div className="no-results"><h2>Hier ist noch kein Bild.</h2><p>Für diese Auswahl gibt es keine Produkte.</p><button className="button button-secondary" onClick={reset}>Filter zurücksetzen</button></div>}</div></div><div className="catalog-note"><span>109 Quellprodukte inklusive archivierter Veranstaltungen · {catalog.length} aktuell im Vorschaukatalog</span><span>Preise inkl. MwSt., zzgl. Versand · Vorschau ohne Zahlungsfunktion</span></div>{mobile&&<Dialog open={filters} onClose={()=>setFilters(false)} label="Produktfilter" className="filter-dialog"><div className="dialog-heading"><h2>Deine Auswahl.</h2><button onClick={()=>setFilters(false)} aria-label="Filter schließen"><X/></button></div><div className="mobile-filter-content">{filterContent}</div><button className="button primary" onClick={()=>setFilters(false)}>{result.length} Produkte ansehen</button></Dialog>}</div>
}
