"use client";
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useInView} from 'motion/react';
import {animate,createTimeline,stagger} from 'animejs';
import {ArrowRight,ArrowUpRight,MoveDown,Grid2X2,Layers,Focus} from 'lucide-react';
import dynamic from 'next/dynamic';
import {Spotlight} from './ui/spotlight-new';
import {useMotionEnabled} from '@/lib/motion';
const Darkroom=dynamic(()=>import('./darkroom'),{ssr:false});
export function Hero(){
 const ref=useRef<HTMLDivElement>(null);const [grid,setGrid]=useState(false);const enabled=useMotionEnabled();const visible=useInView(ref,{amount:.05});
 useEffect(()=>{const el=ref.current;if(!el||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const tl=createTimeline({defaults:{duration:650,ease:'outCubic'}}).add(el.querySelectorAll('.hero-enter'),{translateY:[22,0],opacity:[.1,1],delay:stagger(65)},0).add(el.querySelectorAll('.film-strip'),{translateX:[90,0],opacity:[.2,1],delay:stagger(90)},180);return()=>{tl.revert()};},[]);
 function arrange(){const next=!grid;setGrid(next);if(enabled)animate('.hero-visual .film-strip',{rotate:next?[2,0]:[-2,0],scale:[.97,1],duration:600,ease:'outCubic'});}
 return <section className="hero section-wrap" ref={ref}><div className="hero-copy"><div className="eyebrow hero-enter"><span className="tiny-cross">+</span> FOTOGRAFIE MIT SUBSTANZ. SEIT 1973.</div><h1 className="hero-enter">Analog.<br/><em>Für immer.</em></h1><p className="hero-enter">Dein Blick. Dein Film. Unser Handwerk.<br/>Filme, Kameras und ein eigenes Labor.<br/>Mitten in Fürth.</p><div className="hero-actions hero-enter"><Link href="/filmentwicklung" className="button primary">Film entwickeln <ArrowUpRight size={19}/></Link><Link href="/shop" className="button button-secondary">Analog shoppen <ArrowRight size={17}/></Link></div><div className="hero-footnote hero-enter"><span className="status-led"/><span>ECHTES LABOR. ECHTE MENSCHEN.</span><span className="hero-coordinate">49°28′ N · 10°59′ O</span></div></div>
 <div className={`hero-visual ${grid?'contact-view':''}`}><Darkroom/>{enabled&&visible&&<div className="hero-spotlight"><Spotlight gradientFirst="radial-gradient(68% 68% at 55% 31%, #dcc7a718 0%, #dc4d220a 50%, transparent 80%)" gradientSecond="radial-gradient(50% 50% at 50% 50%, #f5e5d711, transparent 80%)" gradientThird="radial-gradient(50% 50% at 50% 50%, #f5e5d707, transparent 80%)" duration={18} xOffset={35}/></div>}<div className="darkroom-grid" aria-hidden="true"/><div className="darkroom-label"><Focus size={15}/><span>DER BILDERFÜRST / FILM LAB</span><span className="live-dot"/></div><div className="negative-position rear"><div className="film-strip"><div className="sprockets"/><div className="film-photos"><figure><img src="/images/store-front.webp" alt="Die echte Schaufenster-Galerie des Bilderfürst" width={600} height={400}/><figcaption>FÜRTH · ALEXANDERSTRASSE 2</figcaption></figure><figure><img src="/images/film-rolls.webp" alt="Filmrollen aus dem eigenen Labor" width={600} height={400}/><figcaption>FILM LAB / C-41</figcaption></figure></div><div className="sprockets"/></div></div><div className="negative-position front"><div className="film-strip"><div className="sprockets"/><div className="film-photos"><figure><img src="/images/scan-adonal.webp" alt="Echter Kodak Tri-X Laborscan: Porsche in Schwarzweiß" width={1200} height={800} fetchPriority="high"/><figcaption>400TX · 23A <span>▶</span></figcaption></figure><figure><img src="/images/store-inside.webp" alt="Einblick in das Fotogeschäft Bilderfürst Fürth" width={600} height={400}/><figcaption>ANALOG STORE · 24A <span>▶</span></figcaption></figure></div><div className="sprockets"/></div></div><span className="film-vertical">LIGHT. CHEMISTRY. TIME.</span><div className="hero-visual-bottom"><span><b>01</b> / KONTAKTBOGEN</span><button onClick={arrange} aria-pressed={grid}>{grid?<Layers size={15}/>:<Grid2X2 size={15}/>} {grid?'Freie Ansicht':'Im Raster ansehen'}</button></div></div>
 <a href="#entdecken" className="hero-scroll"><MoveDown size={15}/><span>WEITER ENTDECKEN</span></a></section>
}
