"use client";
import Link from 'next/link';
import {useState} from 'react';
import {ArrowUpRight,ArrowRight,Film,ScanLine,Printer,ContactRound,Camera,MapPin,X,Plus,Focus} from 'lucide-react';
import {Hero} from './hero';
import {ProductCard} from './product-card';
import {Reveal} from './reveal';
import {featured,bySlug,formatPrice} from '@/lib/catalog';
import {CardContainer,CardBody,CardItem} from './ui/3d-card';
import {Lens} from './ui/lens';
import {Compare} from './ui/compare';
import {TracingBeam} from './ui/tracing-beam';
import {ParallaxScroll} from './ui/parallax-scroll';
import {Dialog} from './dialog';
import {HiggsfieldProp,PropPoster} from './higgsfield-prop';
import {ShutterImage} from './photographic-motion';
const quick=[{icon:Film,label:'Film entwickeln',detail:'C-41 · S/W · E-6',url:'/filmentwicklung'},{icon:Camera,label:'Analog Store',detail:'Filme & Kameras',url:'/shop'},{icon:ContactRound,label:'Pass- & Bewerbungsbilder',detail:'Bei uns im Fotostudio',url:'/services'},{icon:ScanLine,label:'Digitalisieren',detail:'Erinnerungen bewahren',url:'/digitalisierung'},{icon:Printer,label:'FineArt Prints',detail:'Vom Bild zum Lieblingsstück',url:'/i/fineart-prints'}];
export function Home(){
 const [large,setLarge]=useState<string|null>(null);const camera=bySlug('pentax-17')!;
 return <><Hero/><div className="quick-services" id="entdecken">{quick.map(({icon:Icon,label,detail,url})=><Link href={url} key={label}><Icon size={25} strokeWidth={1.3}/><span><strong>{label}</strong><small>{detail}</small></span><ArrowUpRight size={15}/></Link>)}</div>
 <Reveal className="section-wrap film-section"><div className="section-heading" data-reveal><div><span className="eyebrow"><span className="section-number">01 /</span> DER NÄCHSTE FILM WARTET</span><h2>Für deinen nächsten Blick.</h2></div><Link href="/shop?category=Filme" className="text-link">Alle Filme entdecken <ArrowUpRight size={20}/></Link></div><div className="home-product-grid">{featured.map((p,i)=><div data-settle key={p.slug}><ProductCard product={p} index={i}/></div>)}</div><div className="catalog-note"><span>35MM · 120 · FARBE · SCHWARZWEISS · SOFORTBILD</span><span>Preise inkl. MwSt., zzgl. Versand · Quellstand 04.10.2026</span></div></Reveal>
 <section className="lab-section"><div className="lab-photo"><img src="/images/film-rolls.webp" alt="Belichtete Kleinbildfilme im Bilderfürst-Labor" width={1200} height={800} loading="lazy"/><span className="photo-tag">KEIN UMWEG. UNSER EIGENES LABOR.</span></div><div className="lab-copy"><span className="eyebrow"><span className="section-number">02 /</span> ENTWICKELT IN FÜRTH</span><h2>Du fängst Licht ein.<br/><em>Wir machen Bilder draus.</em></h2><p>C-41 im Fujifilm Minilab. Schwarzweiß in der Jobo-Rotation. Scans mit dem Noritsu HS-1800. Dein Film ist bei uns in erfahrenen Händen.</p><div className="process-tags"><span>C-41</span><span>SCHWARZWEISS</span><span>E-6</span></div><Link className="button primary" href="/filmentwicklung">Deinen Film konfigurieren <ArrowUpRight size={19}/></Link><div className="lab-footer"><span>35MM AB <b>7,00 €</b></span><span>120 AB <b>9,00 €</b></span><Link href="/kontakt">Abgeben oder einschicken <ArrowRight size={15}/></Link></div></div></section>
 <Reveal className="section-wrap camera-section"><div className="camera-copy" data-reveal><span className="eyebrow"><span className="section-number">03 /</span> WENIGER BILDSCHIRM. MEHR BLICK.</span><h2>Ein neuer Anfang.<br/>Ein halbes Format.</h2><p>Die Pentax 17. Filmtransport von Hand. Zonenfokus. 72 Bilder auf einem 36er Film. Eine Kamera, die Lust aufs Fotografieren macht.</p><Link href="/p/pentax-17" className="text-link">Pentax 17 kennenlernen <ArrowUpRight size={20}/></Link><a className="vintage-link" href="https://www.ebay.de/usr/bilderfuerstfuerth" target="_blank" rel="noopener noreferrer">Lieber ein Klassiker? Unsere analogen Schätze ↗</a></div><CardContainer containerClassName="camera-container !py-0" className="w-full"><CardBody className="camera-feature !h-auto !w-full"><CardItem translateZ={22} className="!w-full"><div className="camera-topline"><span className="eyebrow">PENTAX 17 / HALBFORMAT</span><Focus size={19}/></div><Lens zoomFactor={1.7} lensSize={180}><img src={camera.images[0]} alt="Die echte Pentax 17 im Bilderfürst-Ladengeschäft" width={750} height={500} loading="lazy"/></Lens></CardItem><div className="camera-feature-bottom"><span>Eine Rolle. Doppelt so viele Bilder.<strong>{formatPrice(camera.price)}</strong></span><Link href="/p/pentax-17" className="round-link" aria-label="Pentax 17 Details"><ArrowUpRight size={25}/></Link></div></CardBody></CardContainer></Reveal>
 <section className="optical-section"><div className="optical-copy"><span className="eyebrow">LICHTWEG / OPTISCHES HANDWERK</span><h2>Alles beginnt<br/><em>mit Licht.</em></h2><p>Ein kleiner Augenblick. Eine bewusste Entscheidung. Vom ersten Licht auf dem Film bis zum fertigen Bild begleiten wir deinen Blick.</p><Link href="/lab" className="text-link">Unser Handwerk entdecken <ArrowUpRight size={18}/></Link><span className="mono">BLENDE · BELICHTUNG · BILD</span></div><HiggsfieldProp kind="Aperture"/></section>
 <section className="sample-section section-wrap"><div className="sample-copy"><span className="eyebrow">DEIN FILM. DEIN ENTWICKLER.</span><h2>Der Unterschied<br/>liegt im Detail.</h2><p>Adonal oder D-76? Vergleiche unsere echten Kodak Tri-X-Aufnahmen. Auf Anfrage entwickeln wir deinen Schwarzweißfilm im gewünschten Entwickler.</p><Link href="/lab" className="text-link">Ein Blick ins Labor <ArrowUpRight size={19}/></Link><small>Labormuster: Adonal 1+25, 7:00 Min. / D-76 1+0, 6:45 Min.</small></div><Compare firstImage="/images/scan-adonal.webp" secondImage="/images/scan-d76.webp"/></section>
 <section className="section-wrap service-section"><div className="section-heading"><div><span className="eyebrow"><span className="section-number">04 /</span> MEHR ALS FILM</span><h2>Was aus Bildern werden kann.</h2></div><Link href="/services" className="text-link">Unsere Services <ArrowUpRight size={20}/></Link></div><div className="service-cards"><Link href="/digitalisierung" className="service-card digitize"><PropPoster kind="Reel"/><span className="mono">01 — DIGITALISIERUNG</span><h3>Gestern aufgenommen.<br/>Morgen noch da.</h3><p>Negative, Dias, Filme, Video und Audio.<br/>Wir bringen deine Erinnerungen ins Heute.</p><span className="service-card-link">Erinnerungen bewahren <ArrowUpRight size={19}/></span></Link><Link href="/i/fineart-prints" className="service-card"><PropPoster kind="Prints"/><span className="mono">02 — FINEART PRINTS</span><h3>Ein Bild verdient<br/>mehr als einen Bildschirm.</h3><p>FineArt auf ausgewählten Papieren.<br/>Bis A3+ direkt in unserem Fürther Geschäft.</p><span className="service-card-link">Drucke entdecken <ArrowUpRight size={19}/></span></Link><Link href="/services" className="service-card"><ContactRound size={28} strokeWidth={1}/><span className="mono">03 — FOTOSTUDIO</span><h3>Gut aussehen.<br/>Du selbst bleiben.</h3><p>Passbilder ohne Termin.<br/>Bewerbungsbilder mit Zeit für dich.</p><span className="service-card-link">Zum Fotostudio <ArrowUpRight size={19}/></span></Link></div></section>
 <section className="street-section"><div className="section-wrap"><div className="section-heading"><div><span className="eyebrow"><span className="section-number">05 /</span> BILDER GEHÖREN NACH DRAUSSEN</span><h2>Unsere Street Gallery.</h2></div><span className="gallery-open"><span className="status-led"/> IM SCHAUFENSTER. RUND UM DIE UHR.</span></div><p className="street-intro">Neun analoge Bilder. Ein Schaufenster. Immer etwas zu entdecken.<br/>Seit 2020 an der Ecke Schwabacher Straße / Alexanderstraße.</p><ParallaxScroll images={[{src:'/images/scan-adonal.webp',caption:'Kodak Tri-X · Adox Adonal'},{src:'/images/store-front.webp',caption:'Das echte Galerie-Schaufenster'},{src:'/images/scan-hc110.webp',caption:'Kodak Tri-X · Kodak HC-110'}]} onSelect={setLarge}/><div className="gallery-note"><span>Labormuster und Original-Schaufenster · Darstellungskonzept, keine aktuelle Ausstellung.</span><Link href="/galerie" className="text-link">Galerie entdecken <ArrowUpRight size={19}/></Link></div></div></section>
 <section className="section-wrap history-preview"><div><span className="eyebrow"><span className="section-number">06 /</span> EIN FAMILIENALBUM MIT ZUKUNFT</span><h2>Drei Generationen.<br/><em>Ein Auge fürs Bild.</em></h2><Link href="/geschichte" className="text-link">Unsere Geschichte <ArrowUpRight size={20}/></Link></div><TracingBeam className="history-preview-beam"><div className="history-mini"><span>1935</span><p>Ernst Dittmer beginnt bei Foto Seitz in Nürnberg.</p></div><div className="history-mini"><span>1973</span><p>Wulf und Klaus Dittmer gründen Bilderfürst in Erlangen.</p></div><div className="history-mini"><span>2001</span><p>Jan Dittmer übernimmt Bilderfürst Fürth. Die dritte Generation.</p></div></TracingBeam></section>
 <section className="visit-section"><div className="visit-photo"><img src="/images/store-front.webp" alt="Original-Ladengeschäft und Street Gallery, Alexanderstraße 2" width={1200} height={800} loading="lazy"/></div><div className="visit-copy"><span className="eyebrow"><MapPin size={14}/> WIR SIND HIER. FÜR DICH.</span><h2>Online entdeckt.<br/>In Fürth zu Hause.</h2><p>Bring deinen Film, deine Fragen oder einfach<br/>deine Neugier mit. Wir freuen uns auf dich.</p><div className="visit-address"><strong>Alexanderstraße 2 · 90762 Fürth</strong><span>Mo–Fr 09:30–18:30 / Sa 09:30–16:30</span></div><Link href="/kontakt" className="button primary">Besuch uns <ArrowUpRight size={19}/></Link><a href="tel:+49911774202" className="text-link">0911 774202</a></div></section>
 <Dialog open={!!large} onClose={()=>setLarge(null)} label="Fotografie vergrößert" className="image-dialog"><button className="lightbox-close" onClick={()=>setLarge(null)} aria-label="Bild schließen"><X/></button>{large&&<ShutterImage src={large} alt="Vergrößerte Originalaufnahme aus der Bilderfürst-Website"/>}</Dialog></>
}
