"use client";
import {useState} from 'react';
import Link from 'next/link';
import {X,Search,Minus,Plus,Trash2,ArrowRight,ArrowUpRight,ShoppingBag} from 'lucide-react';
import {Dialog} from './dialog';
import {useStore} from './store-context';
import {bySlug,catalog,formatPrice,matchesQuery} from '@/lib/catalog';
export function ShopOverlays(){
 const s=useStore();const [q,setQ]=useState('');const results=catalog.filter(p=>matchesQuery(p,q)).sort((a,b)=>Number(b.inStock)-Number(a.inStock)).slice(0,10);
 const total=s.lines.reduce((sum,l)=>sum+(bySlug(l.slug)?.price||0)*l.quantity,0);
 return <><Dialog open={s.cartOpen} onClose={()=>s.setCartOpen(false)} label="Warenkorb Vorschau" className="cart-drawer"><div className="dialog-heading"><h2>Dein Warenkorb<span className="mono"> / {s.lines.reduce((a,l)=>a+l.quantity,0)}</span></h2><button onClick={()=>s.setCartOpen(false)} aria-label="Warenkorb schließen"><X/></button></div><div className="review-note"><i/> Vorschau · Es werden keine Bestellungen ausgelöst.</div>
 {s.lines.length===0?<div className="cart-empty"><ShoppingBag size={48} strokeWidth={1}/><h3>Platz für deinen nächsten Film.</h3><p>Entdecke Filme, Kameras und alles für dein Labor.</p><Link className="button primary" href="/shop" onClick={()=>s.setCartOpen(false)}>Zum Shop <ArrowRight size={18}/></Link></div>:<><div className="cart-lines">{s.lines.map(l=>{const p=bySlug(l.slug);if(!p)return null;return <div className="cart-line" key={l.slug}><Link href={`/p/${l.slug}`} onClick={()=>s.setCartOpen(false)}><img src={p.images[0]} alt={p.name} width={90} height={90}/></Link><div><Link href={`/p/${l.slug}`} onClick={()=>s.setCartOpen(false)}>{p.name}</Link><p>{formatPrice(p.price)}</p><div className="quantity"><button aria-label={`${p.name}: Menge verringern`} onClick={()=>s.update(l.slug,l.quantity-1)}><Minus size={13}/></button><span>{l.quantity}</span><button aria-label={`${p.name}: Menge erhöhen`} disabled={l.quantity>=99} onClick={()=>s.update(l.slug,l.quantity+1)}><Plus size={13}/></button></div><a href={p.source} target="_blank" rel="noopener noreferrer" className="source-link">Im Originalshop kaufen <ArrowUpRight size={12}/></a></div><button className="remove-line" aria-label={`${p.name} entfernen`} onClick={()=>s.update(l.slug,0)}><Trash2 size={15}/></button></div>})}</div><div className="cart-summary"><div><span>Zwischensumme</span><strong>{formatPrice(total)}</strong></div><p>inkl. MwSt. · Versand im bestehenden Shop.</p><Link className="button primary" href="/checkout" onClick={()=>s.setCartOpen(false)}>Vorschau ansehen <ArrowRight size={18}/></Link><p className="small">Preise & Verfügbarkeit: Quellstand 04.10.2026.</p></div></>}
 </Dialog><Dialog open={s.searchOpen} onClose={()=>s.setSearchOpen(false)} label="Produktsuche" className="search-dialog"><div className="dialog-heading"><h2>Was suchst du?</h2><button aria-label="Suche schließen" onClick={()=>s.setSearchOpen(false)}><X/></button></div><div className="search-input"><Search size={21}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Portra 400, 120, C-41, Jobo …" aria-label="Produkte durchsuchen"/></div><div className="search-results">{results.length===0?<p>Keine Produkte gefunden. Versuche einen anderen Suchbegriff.</p>:results.map(p=><Link key={p.slug} href={`/p/${p.slug}`} onClick={()=>s.setSearchOpen(false)}><img src={p.images[0]} alt="" width={64} height={64}/><span><strong>{p.name}</strong><small>{p.inStock?'Auf Lager (Quellstand)':'Lieferzeit anfragen'}</small></span><span>{formatPrice(p.price)}<ArrowUpRight size={16}/></span></Link>)}</div><Link href={`/shop?q=${encodeURIComponent(q)}`} className="text-link" onClick={()=>s.setSearchOpen(false)}>Alle Ergebnisse im Shop <ArrowRight size={16}/></Link></Dialog></>
}
